server:
  port: ${APP_PORT:8081}
  servlet:
    context-path: /api/v1
  error:
    include-stacktrace: never

keycloak:
  introspect:
    publicKeyProvider: ${PUBLIC_KEY_PROVIDER:authorization_server}
    #publicKeyProvider: ${PUBLIC_KEY_PROVIDER:public_key_file}
    publicKeyFile: ${PUBLIC_KEY_FILE:jwks.yaml}